"""Compatibility bridge for Ollama tools.

This module keeps the existing tool contract while routing chat calls through
the shared Ollama client in app/services/ollama_client.py.
"""

from dataclasses import dataclass
import os
import re
from typing import Any, Optional

from .services.ollama_client import OllamaClient


DEFAULT_OLLAMA_MODEL = "qwen2.5:7b-instruct"


@dataclass
class AskOllamaResult:
    status: str
    answer: str
    model_used: str
    duration_ms: float
    prompt_tokens: int
    response_tokens: int
    error: Optional[str] = None


@dataclass
class OllamaPythonResult:
    status: str
    model_used: str
    generation_time_ms: float
    total_time_ms: float
    generated_code: Optional[str] = None
    validation_error: Optional[str] = None
    exec_result: Optional[dict[str, Any]] = None


TASK_SYSTEM_PROMPTS = {
    "summarize": "Fasse den Inhalt kurz und praezise zusammen.",
    "translate": "Uebersetze den Inhalt treu und natuerlich.",
    "analyze": "Analysiere strukturiert und gib klare Schluesse.",
    "classify": "Klassifiziere den Inhalt und gib die Klasse mit kurzer Begruendung.",
    "format": "Formatiere den Inhalt wie gefordert, ohne zusaetzliche Erklaerungen.",
    "generate": "Erzeuge hochwertigen Inhalt gemaess Aufgabe.",
    "extract": "Extrahiere die relevanten Informationen strukturiert.",
}


def _default_model() -> str:
    return os.environ.get("JARVIS_OLLAMA_DEFAULT_MODEL", DEFAULT_OLLAMA_MODEL)


def _extract_python_code(text: str) -> Optional[str]:
    if not text:
        return None

    fenced = re.search(r"```python\s*(.*?)```", text, re.DOTALL | re.IGNORECASE)
    if fenced:
        return fenced.group(1).strip()

    generic = re.search(r"```\s*(.*?)```", text, re.DOTALL)
    if generic:
        return generic.group(1).strip()

    # Fallback if model returned raw code without fences.
    if "def " in text or "import " in text or "print(" in text:
        return text.strip()

    return None


def ask_ollama(
    prompt: str,
    task_type: str = "analyze",
    system_prompt: Optional[str] = None,
    max_tokens: Optional[int] = None,
) -> AskOllamaResult:
    """Ask Ollama through shared chat client."""
    model = _default_model()
    client = OllamaClient()
    effective_system = system_prompt or TASK_SYSTEM_PROMPTS.get(task_type)

    chat_result = client.chat(
        model=model,
        messages=[{"role": "user", "content": prompt}],
        system=effective_system,
        max_tokens=max_tokens if max_tokens is not None else 1500,
        temperature=0.2,
    )

    if not chat_result.success:
        return AskOllamaResult(
            status="error",
            answer="",
            model_used=model,
            duration_ms=chat_result.duration_ms,
            prompt_tokens=chat_result.prompt_tokens,
            response_tokens=chat_result.completion_tokens,
            error=chat_result.error,
        )

    return AskOllamaResult(
        status="success",
        answer=chat_result.content,
        model_used=chat_result.model,
        duration_ms=chat_result.duration_ms,
        prompt_tokens=chat_result.prompt_tokens,
        response_tokens=chat_result.completion_tokens,
    )


def generate_and_execute_python(
    task_description: str,
    context: Optional[str] = None,
    model: Optional[str] = None,
    user_id: Optional[str] = None,
) -> OllamaPythonResult:
    """Generate code via Ollama and execute via existing sandbox tool path."""
    del user_id  # Kept for API compatibility.

    selected_model = model or _default_model()
    prompt = (
        "Write Python code for the task below. Return ONLY Python code in a single "
        "```python fenced block.\n\n"
        f"Task:\n{task_description}\n"
    )
    if context:
        prompt += f"\nContext:\n{context}\n"

    client = OllamaClient()
    generation = client.chat(
        model=selected_model,
        messages=[{"role": "user", "content": prompt}],
        system="You are a senior Python engineer. Return valid Python only.",
        max_tokens=1800,
        temperature=0.1,
    )

    if not generation.success:
        return OllamaPythonResult(
            status="error",
            model_used=selected_model,
            generation_time_ms=generation.duration_ms,
            total_time_ms=generation.duration_ms,
            validation_error=generation.error,
        )

    code = _extract_python_code(generation.content)
    if not code:
        return OllamaPythonResult(
            status="error",
            model_used=generation.model,
            generation_time_ms=generation.duration_ms,
            total_time_ms=generation.duration_ms,
            validation_error="No executable Python code generated by Ollama.",
        )

    # Route execution through existing sandbox tool path for policy compatibility.
    from .tool_modules.sandbox_tools import tool_execute_python

    exec_result = tool_execute_python(code=code, reason="ollama_python_bridge")
    if exec_result.get("error"):
        return OllamaPythonResult(
            status="error",
            model_used=generation.model,
            generation_time_ms=generation.duration_ms,
            total_time_ms=generation.duration_ms,
            generated_code=code,
            validation_error=str(exec_result.get("error")),
            exec_result=None,
        )

    return OllamaPythonResult(
        status=str(exec_result.get("status", "success")),
        model_used=generation.model,
        generation_time_ms=generation.duration_ms,
        total_time_ms=generation.duration_ms,
        generated_code=code,
        exec_result=exec_result,
    )
